name: Auto Assign

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Assignees
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: LeoRZm
